//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Available> Availables { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CounterOfferForAvailable> CounterOfferForAvailables { get; set; }
        public DbSet<CounterOfferForNeed> CounterOfferForNeeds { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Need> Needs { get; set; }
        public DbSet<OfferForAvailable> OfferForAvailables { get; set; }
        public DbSet<OfferForNeed> OfferForNeeds { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    }
}
