//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterOfferForAvailable
    {
        public int Id { get; set; }
        public string counter_offer_user { get; set; }
        public string description { get; set; }
        public byte[] created_at { get; set; }
        public Nullable<bool> accepted_flag { get; set; }
    }
}
