//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterOfferForNeed
    {
        public int Id { get; set; }
        public string Counter_Offer_User { get; set; }
        public string Description { get; set; }
        public byte[] Created_at { get; set; }
        public bool Accepted_flag { get; set; }
    }
}
