//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Need
    {
        public int Id { get; set; }
        public string User_Email_Needs { get; set; }
        public string Category { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Accepted_Flag { get; set; }
    }
}
