//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferForNeed
    {
        public int Id { get; set; }
        public byte[] Created_At { get; set; }
        public bool Accepted_Flag { get; set; }
        public string User_Making_Offer { get; set; }
        public string Description { get; set; }
        public int Need_ID { get; set; } 
    }
}
