//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferForAvailable
    {
        public int Id { get; set; }
        public byte[] CreatedAt { get; set; }
        public bool Accepted_Flag { get; set; }
        public string User_making_offer { get; set; }
        public string Description { get; set; }
    }
}
