//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
namespace BarterWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string LinkToEbay { get; set; }
        public string LinkToAmazon { get; set; }
        public string Email { get; set; }
        public string TwitterAccount { get; set; }
        public string BlogURL { get; set; }
        public string LinkedInUrl { get; set; }
        public string CompanyUrl { get; set; }
    }
}
*/